name: Android

on:
  push:
    branches: [ cmake ]
  pull_request:
    branches: [ cmake ]

env:
  PROJECT_NAME: juicysf
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/android/app/build/outputs/apk/release/
  PREBUILT_DIR: prebuilt
  FLUIDSYNTH_VERSION: 2.2.4
  FLUIDSYNTH_POSTFIX: android24
  LINUX_DEPS: "libasound2-dev \
               libcurl4-openssl-dev \
               libfreetype6-dev \
               libglu1-mesa-dev \
               libomp-dev \
               libsndfile1-dev \
               libsystemd-dev \
               libxslt1-dev \
               libwebkit2gtk-4.0-dev \
               libx11-dev \
               libxext-dev \
               libxinerama-dev \
               ninja-build"

jobs:
  build:
    runs-on: ubuntu-latest
    name: gradle
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Linux - Install Deps
        run: sudo apt-get update && sudo apt install ${{env.LINUX_DEPS}}

      - name: Download Prebuilt Fluidsynth Binaries
        run: wget https://github.com/FluidSynth/fluidsynth/releases/download/v${{env.FLUIDSYNTH_VERSION}}/fluidsynth-${{env.FLUIDSYNTH_VERSION}}-${{env.FLUIDSYNTH_POSTFIX}}.zip

      - name: Unpack Fluidsynth
        run: |
            unzip fluidsynth-${{env.FLUIDSYNTH_VERSION}}-${{env.FLUIDSYNTH_POSTFIX}}.zip -d ${{env.PREBUILT_DIR}} **/libfluidsynth.so
            unzip fluidsynth-${{env.FLUIDSYNTH_VERSION}}-${{env.FLUIDSYNTH_POSTFIX}}.zip -d ${{env.PREBUILT_DIR}}  include/**

      - name: Unpack Fluidsynth Dependencies
        run: unzip fluidsynth-${{env.FLUIDSYNTH_VERSION}}-${{env.FLUIDSYNTH_POSTFIX}}.zip -d android/app/src/main/tmp *.so -x lib/**/libfluidsynth.so

      - name: Move Fluidsynth Dependencies
        run: mv android/app/src/main/tmp/lib android/app/src/main/jniLibs

      - name: Gradle - Grant Permission
        working-directory: ./android
        run: chmod +x gradlew

      - name: Gradle - Build
        working-directory: ./android
        run: ./gradlew build

      - name: Zip
        working-directory: ${{env.BUILD_DIR}}
        run: cmake -E tar cv ${{env.PROJECT_NAME}}_android.7z --format=7zip *.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.PROJECT_NAME}}_android
          path: ${{env.BUILD_DIR}}/${{env.PROJECT_NAME}}_android.7z
          if-no-files-found: error
          retention-days: 1
